name: switch_up
version: 0.0.3+2
description: An animated toggle switch which can be fully customized with desired width, colors, text, corner radius, animation etc. It also maintains selection state.
homepage: https://github.com/ketan-glitch/switch_up
repository: https://github.com/ketan-glitch/switch_up
issue_tracker: https://github.com/ketan-glitch/switch_up

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
