name: switch_up
version: 0.0.1
homepage: https://github.com/ketan-glitch/switch_up
description: An animated switch.

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
